# Generated by Django 2.1.3 on 2018-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('FirstName', models.TextField()),
                ('MiddleName', models.TextField()),
                ('LastName', models.TextField()),
            ],
        ),
    ]
