# Generated by Django 2.1.3 on 2018-11-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField()),
                ('MiddleName', models.TextField()),
                ('LastName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='HaveChildren',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='children',
            name='PersonInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PersonInfo'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Position'),
        ),
    ]
