# Generated by Django 2.1.3 on 2018-11-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181117_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='PersonInfo',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='City',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='Country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='MiddleName',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Children',
        ),
    ]
